name: Multiple Jobs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo Building code
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo test
