name: Reusable Workflow Example

on:
  push:
    paths:
    - '.github/workflows/reuse.yml'
    
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: setup
      run: echo setup
  build-deploy:
    needs: setup
    uses: ./.github/workflows/reusable-workflow.yml
